Update linux_script

diff --git a/linux_script b/linux_script
--- a/linux_script
+++ b/linux_script
@@ -122,4 +122,21 @@ do
   echo "YourName"
   i=$((i + 1))
 done
-=======================================================================================================
+==
+#!/bin/bash
+
+# First command
+chage -M 180 nari
+
+# Check if the first command was successful
+if [ $? -eq 0 ]; then
+    echo "Password expiry updated successfully."
+
+    # Second command
+    chage -W 7 nari
+    echo "Warning days set to 7."
+else
+    echo "Failed to update password expiry. Skipping warning setup."
+fi
+
+=====================================================================================================
